service: step-functions-challenge

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    S3_BUCKET: "dimitris3"
    DB_SECRET_ID: db-secrets   
    DB_PORT: 5432    

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:GetObject"
      - "s3:ListBucket"
    Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
    
  - Effect: "Allow"
    Action:
      - "ssm:GetParameter"
      - "ssm:GetParameters"
      - "ssm:GetParameterHistory"
    Resource: "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/${self:provider.environment.DB_SECRET_ID}"
    
  - Effect: "Allow"
    Action:
      - "s3:GetObject"
      - "s3:ListBucket"
    Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
  
  - Effect: "Allow"
    Action:
      - "rds:DescribeDBInstances"
      - "rds:DescribeDBClusters"
    Resource: "*"
  
  - Effect: "Allow"
    Action:
      - "rds-data:ExecuteStatement"  
    Resource: "arn:aws:rds:${self:provider.region}:${aws:accountId}:cluster:${self:provider.environment.DB_NAME}"
  
  - Effect: "Allow"
    Action:
      - "rds:Connect"
    Resource: "*"

functions:
  lambda1:
    handler: lambdas/lambda1/handler.handler
    events:
      - http:
          path: lambda1
          method: post

  lambda2:
    handler: lambdas/lambda2/handler.handler
    vpc:
      securityGroupIds:
        - sg-0250c50609b0a61d5  
      subnetIds:
        - subnet-08c5033fba30bb485  

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}

stepFunctions:
  stateMachines:
    ProcessCSV:
      definition:
        StartAt: Lambda1
        States:
          Lambda1:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:service}-${self:provider.stage}-lambda1
            Parameters:
              link: "https://dados.antt.gov.br/dataset/ef0171a8-f0df-4817-a4ed-b4ff94d87194/resource/aa60ce3a-033a-4864-81dc-ae32bea866e5/download/demostrativo_acidentes_viaaraucaria.csv"
            Next: Lambda2
          Lambda2:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:service}-${self:provider.stage}-lambda2
            End: true

