service: accidentes-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  environment:
    DB_HOST: ${ssm:/db_host}
    DB_USER: ${ssm:/db_user}
    DB_PASSWORD: ${ssm:/db_password}
    DB_NAME: ${ssm:/db_name}
    S3_BUCKET_NAME: ${ssm:/s3_bucket_name}

functions:
  lambda1:
    handler: lambdas/lambda1/handler.handler
    events:
      - http:
          path: lambda1
          method: post
    environment:
      S3_BUCKET_NAME: ${self:provider.environment.S3_BUCKET_NAME}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
        Resource: arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/processed/*

  lambda2:
    handler: lambdas/lambda2/handler.handler
    events:
      - http:
          path: lambda2
          method: post
    environment:
      DB_HOST: ${self:provider.environment.DB_HOST}
      DB_USER: ${self:provider.environment.DB_USER}
      DB_PASSWORD: ${self:provider.environment.DB_PASSWORD}
      DB_NAME: ${self:provider.environment.DB_NAME}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:GetObject"
        Resource: arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/processed/*
      - Effect: "Allow"
        Action:
          - "rds:ExecuteStatement"
        Resource: arn:aws:rds:us-east-1:${aws:accountId}:db:your-db-instance-id

stepFunctions:
  stateMachines:
    accidenteStateMachine:
      definition:
        StartAt: "Lambda1Task"
        States:
          Lambda1Task:
            Type: Task
            Resource:
              Fn::GetAtt:
                - lambda1
                - Arn
            Next: Lambda2Task
          Lambda2Task:
            Type: Task
            Resource:
              Fn::GetAtt:
                - lambda2
                - Arn
            End: true

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET_NAME}
        LifecycleConfiguration:
          Rules:
            - Status: Enabled
              ExpirationInDays: 7  # Borra archivos después de 7 días para evitar acumulación
