name: Deploy to AWS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checar código
        uses: actions/checkout@v2

      # Set up AWS credentials
      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      # Install Node.js and dependencies
      - name: Install Node.js and dependencies
        run: |
          # Install Node.js (Make sure to match the version you need)
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          
          # Install Serverless Framework and serverless-offline plugin
          npm install -g serverless
          npm install serverless-offline --save-dev
          npm install  # This installs other dependencies in package.json

      # Deploy with Serverless
      - name: Deploy with Serverless
        run: |
          # Deploy your service using Serverless Framework
          npx serverless deploy --verbose
