name: CI/CD Pipeline for Serverless Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Ensure package.json exists
        run: |
          ls -l # List files to confirm package.json exists

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use Node.js version 16 (LTS) for better stability

      - name: Install dependencies
        run: npm install  # Ensure all dependencies from package.json are installed

      - name: Install Python and dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Install Serverless Framework and Plugins
        run: |
          npm install serverless@3  # Install Serverless Framework version 3 locally
          npm install serverless-offline@8.x --save-dev  # Install serverless-offline plugin for Serverless v3
          npm install serverless-step-functions --save-dev  # If you're using Step Functions, install this plugin

  deploy:
    runs-on: ubuntu-latest
    needs: setup_environment
    environment:
      name: production
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check serverless installation
        run: ./node_modules/.bin/serverless --version  # Use the local installation of serverless

      - name: Deploy with Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          ./node_modules/.bin/serverless deploy --verbose  # Use the local installation of serverless
