name: CI/CD Pipeline for Serverless Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Python and dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Install Serverless Framework version 3
        run: npm install serverless@3 

      - name: Install compatible serverless-offline version
        run: npm install serverless-offline@8.x  # Use a version that supports Serverless v3

  deploy:
    runs-on: ubuntu-latest
    needs: setup_environment
    environment:
      name: production
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy with Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          npx serverless@3 deploy --verbose
