name: CI/CD Pipeline for Serverless Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out code
        uses: actions/checkout@v3

     
      - name: Install PostgreSQL dependencies
        run: sudo apt-get install libpq-dev
        if: runner.os == 'Linux' 


      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  


      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Install serverless-python-requirements plugin
        run: npm install --save serverless-python-requirements

 
      - name: Install serverless-step-functions plugin
        run: npm install --save serverless-step-functions

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
